---
  - name: Install dependencies
    apt: pkg={{item}} state=installed update-cache=yes
    with_items:
      - python-django
      - translate-toolkit
      - python-whoosh
      - python-pil
      - python-libravatar
      - python-babel
      - git
      - mercurial
      - python-social-auth
      - python-django-compressor
      - python-requests-oauthlib
      - python-six
      - python-openid
      - mysql-server
