---
  - name: Reset root pass
    mysql_user: name=root password={{ db_root_pass }} login_user=root login_password={{ db_root_pass }} check_implicit_admin=yes priv=*.*:ALL,GRANT state=present

  - name: Create weblate DB
    mysql_db: name={{ db_name }} encoding=utf-8 state=present login_user=root login_password={{ db_root_pass }}

  - name: Create DB user
    mysql_user: name={{ db_user }} password={{ db_password}} login_user=root login_password={{ db_root_pass }} priv={{ db_name }}.*:ALL,GRANT state=present
